-- Create public.auth_user if it does not exist (global admin table)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='auth_user'
  ) THEN
    CREATE TABLE public.auth_user (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      username VARCHAR(150) NOT NULL UNIQUE,
      email VARCHAR(254) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      is_superadmin BOOLEAN NOT NULL DEFAULT FALSE,
      is_staff BOOLEAN NOT NULL DEFAULT FALSE,
      is_verified BOOLEAN NOT NULL DEFAULT FALSE,
      failed_login_count INTEGER NOT NULL DEFAULT 0,
      locked_until TIMESTAMPTZ NULL,
      last_login_at TIMESTAMPTZ NULL,
      last_password_change_at TIMESTAMPTZ NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    -- helpful indexes
    CREATE INDEX IF NOT EXISTS ix_auth_user_id ON public.auth_user (id);
    CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_user_username ON public.auth_user (username);
    CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_user_email ON public.auth_user (email);
    -- Ensure RLS is disabled (admin table is global)
    ALTER TABLE public.auth_user DISABLE ROW LEVEL SECURITY;
  END IF;
END $$;

