
services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gestiqclouddb_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestiqclouddb_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  admin:
    build:
      context: ./apps/admin
    container_name: admin
    depends_on:
      - backend
    ports:
      - "8081:8081"

  tenant:
    build:
      context: ./apps/tenant
    container_name: tenant
    depends_on:
      - backend
    ports:
      - "8082:8082"

volumes:
  db_data:
