services:
  backend:
    ports:
      - "8000:8000"
    environment:
      # Allow Admin (8081) and Tenant (8082) origins in local
      CORS_ALLOW_ORIGIN_REGEX: "^http://localhost:(8081|8082)$"
      CORS_ALLOW_CREDENTIALS: "true"
      CORS_ALLOW_METHODS: '["*"]'
      CORS_ALLOW_HEADERS: '["*"]'

  admin:
    build:
      args:
        VITE_API_URL: "http://localhost:8000/api"
        VITE_BASE_PATH: "/"
        VITE_ADMIN_ORIGIN: "http://localhost:8081"
        VITE_TENANT_ORIGIN: "http://localhost:8082"
    ports:
      - "8081:8081"

  tenant:
      build:
        args:
          VITE_API_URL: "http://localhost:8082"
          VITE_BASE_PATH: "/"
          VITE_ADMIN_ORIGIN: "http://localhost:8081"
          VITE_TENANT_ORIGIN: "http://localhost:8082"
     # No host port here; edge will publish :8082 and proxy to tenant
     # Keep tenant as a plain static server like PROD

  migrations:
    environment:
      RUN_MIGRATIONS: "1"

  # Dev-only edge that mirrors PROD Cloudflare routing
  edge:
    image: nginx:1.27-alpine
    ports:
      - "8082:80"
    volumes:
      - ./ops/nginx/edge.local.conf:/etc/nginx/conf.d/default.conf:ro
