[tool.pytest.ini_options]
testpaths = ["app/test"]
addopts = "-q"
filterwarnings = [
  "ignore::DeprecationWarning",
]

[tool.black]
line-length = 100
target-version = ["py311"]
exclude = [
  "/migrations/",
]

[tool.isort]
profile = "black"
line_length = 100
skip = ["migrations"]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["migrations"]
