-- Ensure id columns auto-increment for modulos tables

DO $$
BEGIN
  -- modulos_modulo.id
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='modulos_modulo' AND column_name='id'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name='modulos_modulo' AND column_name='id' AND column_default IS NOT NULL
    ) THEN
      BEGIN
        ALTER TABLE public.modulos_modulo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
      EXCEPTION WHEN others THEN
        -- Fallback to sequence default
        BEGIN
          CREATE SEQUENCE IF NOT EXISTS public.modulos_modulo_id_seq OWNED BY public.modulos_modulo.id;
          ALTER TABLE public.modulos_modulo ALTER COLUMN id SET DEFAULT nextval('public.modulos_modulo_id_seq');
        EXCEPTION WHEN others THEN
          NULL;
        END;
      END;
    END IF;
  END IF;

  -- modulos_empresamodulo.id
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='modulos_empresamodulo' AND column_name='id'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name='modulos_empresamodulo' AND column_name='id' AND column_default IS NOT NULL
    ) THEN
      BEGIN
        ALTER TABLE public.modulos_empresamodulo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
      EXCEPTION WHEN others THEN
        BEGIN
          CREATE SEQUENCE IF NOT EXISTS public.modulos_empresamodulo_id_seq OWNED BY public.modulos_empresamodulo.id;
          ALTER TABLE public.modulos_empresamodulo ALTER COLUMN id SET DEFAULT nextval('public.modulos_empresamodulo_id_seq');
        EXCEPTION WHEN others THEN
          NULL;
        END;
      END;
    END IF;
  END IF;

  -- modulos_moduloasignado.id
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='modulos_moduloasignado' AND column_name='id'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name='modulos_moduloasignado' AND column_name='id' AND column_default IS NOT NULL
    ) THEN
      BEGIN
        ALTER TABLE public.modulos_moduloasignado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
      EXCEPTION WHEN others THEN
        BEGIN
          CREATE SEQUENCE IF NOT EXISTS public.modulos_moduloasignado_id_seq OWNED BY public.modulos_moduloasignado.id;
          ALTER TABLE public.modulos_moduloasignado ALTER COLUMN id SET DEFAULT nextval('public.modulos_moduloasignado_id_seq');
        EXCEPTION WHEN others THEN
          NULL;
        END;
      END;
    END IF;
  END IF;
END $$;

