"""Training data for header classifier."""

from typing import Final

TRAINING_DATA: Final[list[tuple[list[str], str]]] = [
    # Recipes - Spanish (PAN KUSI style)
    (["ingredientes", "cantidad", "unidad", "rendimiento", "importe"], "recipes"),
    (["nombre de la receta", "porciones", "costo total ingredientes"], "recipes"),
    (["ingredientes requeridos", "costo unitario", "costo fraccion"], "recipes"),
    # Products - Spanish
    (["nombre", "precio", "cantidad", "categoria"], "products"),
    (["producto", "precio_unitario", "stock", "descripcion"], "products"),
    (["articulo", "costo", "cantidad", "almacen"], "products"),
    (["nombre_producto", "precio_venta", "existencia", "codigo"], "products"),
    (["item", "valor", "unidades", "categoria", "marca"], "products"),
    (["descripcion", "precio", "inventario", "sku", "proveedor"], "products"),
    (["producto", "costo_unitario", "stock_actual", "minimo", "maximo"], "products"),
    (["codigo_barras", "nombre", "precio", "categoria", "subcategoria"], "products"),
    # Products - English
    (["product", "price", "qty", "sku", "stock"], "products"),
    (["name", "unit_price", "quantity", "category"], "products"),
    (["item", "cost", "inventory", "description"], "products"),
    (["product_name", "sale_price", "stock_qty", "barcode"], "products"),
    (["sku", "name", "price", "cost", "stock", "category"], "products"),
    (["product_code", "description", "retail_price", "wholesale_price"], "products"),
    (["item_name", "unit_cost", "quantity_on_hand", "reorder_level"], "products"),
    # Bank transactions - Spanish
    (["fecha", "concepto", "importe", "saldo"], "bank_transactions"),
    (["fecha_operacion", "descripcion", "cargo", "abono", "saldo"], "bank_transactions"),
    (["fecha", "referencia", "movimiento", "monto", "saldo_final"], "bank_transactions"),
    (["fecha_valor", "concepto", "debito", "credito", "saldo"], "bank_transactions"),
    (["fecha", "descripcion", "retiro", "deposito", "saldo_disponible"], "bank_transactions"),
    (["fecha_transaccion", "detalle", "importe", "tipo", "saldo"], "bank_transactions"),
    (["operacion", "fecha", "monto", "referencia", "cuenta"], "bank_transactions"),
    # Bank transactions - English
    (["date", "description", "amount", "balance", "iban"], "bank_transactions"),
    (["transaction_date", "details", "debit", "credit", "balance"], "bank_transactions"),
    (["date", "reference", "amount", "type", "running_balance"], "bank_transactions"),
    (["value_date", "description", "withdrawal", "deposit", "balance"], "bank_transactions"),
    (["posting_date", "narrative", "dr", "cr", "balance"], "bank_transactions"),
    (["date", "payee", "amount", "category", "account_balance"], "bank_transactions"),
    (["transaction_id", "date", "amount", "merchant", "balance"], "bank_transactions"),
    # Invoices - Spanish
    (["factura", "cliente", "total", "iva", "fecha"], "invoices"),
    (["numero_factura", "razon_social", "subtotal", "impuesto", "total"], "invoices"),
    (["folio", "cliente", "importe", "iva", "total", "fecha_emision"], "invoices"),
    (["serie_folio", "receptor", "base", "iva", "total"], "invoices"),
    (["numero", "proveedor", "neto", "iva", "total", "vencimiento"], "invoices"),
    (["factura_numero", "vendedor", "monto", "impuestos", "total_factura"], "invoices"),
    (["documento", "cliente", "subtotal", "iva", "total", "estado"], "invoices"),
    (["nro_factura", "ruc", "cliente", "importe", "igv", "total"], "invoices"),
    # Invoices - English
    (["invoice_number", "vendor", "subtotal", "tax", "total"], "invoices"),
    (["invoice", "customer", "amount", "vat", "total_amount"], "invoices"),
    (["invoice_id", "supplier", "net", "tax", "gross", "due_date"], "invoices"),
    (["inv_no", "client", "subtotal", "sales_tax", "total"], "invoices"),
    (["document_number", "vendor_name", "line_total", "tax_amount", "total"], "invoices"),
    (["invoice_ref", "bill_to", "amount", "vat", "total", "payment_terms"], "invoices"),
    (["number", "customer_name", "net_amount", "tax", "gross_amount"], "invoices"),
    # Expenses - Spanish
    (["gasto", "categoria", "monto", "fecha", "proveedor"], "expenses"),
    (["concepto", "importe", "fecha_gasto", "tipo", "comprobante"], "expenses"),
    (["descripcion_gasto", "valor", "fecha", "categoria", "forma_pago"], "expenses"),
    (["egreso", "monto", "fecha", "rubro", "proveedor"], "expenses"),
    (["tipo_gasto", "importe", "fecha", "justificacion", "aprobado"], "expenses"),
    (["concepto", "costo", "fecha_pago", "departamento", "proyecto"], "expenses"),
    (["gasto_operativo", "monto", "periodo", "cuenta_contable"], "expenses"),
    # Expenses - English
    (["expense", "category", "amount", "date", "receipt"], "expenses"),
    (["expense_type", "cost", "expense_date", "vendor", "payment_method"], "expenses"),
    (["description", "amount", "date", "category", "reimbursable"], "expenses"),
    (["expense_category", "value", "date", "department", "project"], "expenses"),
    (["item", "expense_amount", "date_incurred", "approved_by"], "expenses"),
    (["expense_description", "total", "date", "status", "receipt_number"], "expenses"),
    (["cost_type", "amount", "period", "gl_account", "notes"], "expenses"),
    # Mixed/Ambiguous cases for training robustness
    (["nombre", "precio", "cantidad"], "products"),
    (["fecha", "monto", "saldo"], "bank_transactions"),
    (["factura", "total", "iva"], "invoices"),
    (["gasto", "monto", "fecha"], "expenses"),
]

DOC_TYPES: Final[list[str]] = ["products", "bank_transactions", "invoices", "expenses", "recipes"]

KEYWORDS_BY_DOCTYPE: Final[dict[str, list[str]]] = {
    "recipes": [
        "ingredientes",
        "receta",
        "porciones",
        "rendimiento",
        "costo total ingredientes",
        "formato de costeo",
        "temperatura de servicio",
        "ingredientes requeridos",
    ],
    "products": [
        "producto",
        "product",
        "nombre",
        "name",
        "precio",
        "price",
        "cantidad",
        "quantity",
        "qty",
        "stock",
        "inventario",
        "inventory",
        "sku",
        "codigo",
        "code",
        "barcode",
        "categoria",
        "category",
        "marca",
        "brand",
        "proveedor",
        "supplier",
        "costo",
        "cost",
        "descripcion",
        "description",
        "item",
        "articulo",
        "unidad",
        "unit",
        "almacen",
        "warehouse",
    ],
    "bank_transactions": [
        "fecha",
        "date",
        "concepto",
        "description",
        "importe",
        "amount",
        "saldo",
        "balance",
        "cargo",
        "debit",
        "abono",
        "credit",
        "movimiento",
        "transaction",
        "referencia",
        "reference",
        "cuenta",
        "account",
        "iban",
        "banco",
        "bank",
        "retiro",
        "withdrawal",
        "deposito",
        "deposit",
        "debito",
        "credito",
        "operacion",
        "posting",
    ],
    "invoices": [
        "factura",
        "invoice",
        "cliente",
        "customer",
        "vendor",
        "proveedor",
        "supplier",
        "total",
        "subtotal",
        "iva",
        "vat",
        "tax",
        "impuesto",
        "numero",
        "number",
        "folio",
        "serie",
        "receptor",
        "emisor",
        "fecha_emision",
        "due_date",
        "vencimiento",
        "neto",
        "net",
        "gross",
        "monto",
        "amount",
        "documento",
        "document",
        "rfc",
        "ruc",
        "nit",
    ],
    "expenses": [
        "gasto",
        "expense",
        "egreso",
        "categoria",
        "category",
        "monto",
        "amount",
        "costo",
        "cost",
        "comprobante",
        "receipt",
        "forma_pago",
        "payment",
        "departamento",
        "department",
        "proyecto",
        "project",
        "justificacion",
        "reimbursable",
        "aprobado",
        "approved",
        "tipo_gasto",
        "expense_type",
        "fecha_gasto",
        "expense_date",
        "concepto",
        "rubro",
    ],
}
