-- Rollback: 2025-11-19_900_missing_tables

BEGIN;

DROP TABLE IF EXISTS sector_templates CASCADE;
DROP TABLE IF EXISTS global_action_permissions CASCADE;
DROP TABLE IF EXISTS import_lineages CASCADE;
DROP TABLE IF EXISTS import_audits CASCADE;
DROP TABLE IF EXISTS import_attachments CASCADE;
DROP TABLE IF EXISTS invoices_temp CASCADE;
DROP TABLE IF EXISTS internal_transfers CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS bank_transactions CASCADE;
DROP TABLE IF EXISTS bank_accounts CASCADE;
DROP TABLE IF EXISTS chart_of_accounts CASCADE;
DROP TABLE IF EXISTS inventory_settings CASCADE;
DROP TABLE IF EXISTS company_settings CASCADE;
DROP TABLE IF EXISTS business_hours CASCADE;
DROP TABLE IF EXISTS weekdays CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS currencies CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS assigned_modules CASCADE;
DROP TABLE IF EXISTS company_modules CASCADE;
DROP TABLE IF EXISTS modules CASCADE;

COMMIT;
