"""
SALES MODULE: Use Cases para órdenes de venta.

Implementa:
- Creación de órdenes
- Aprobación
- Conversión a factura
- Descuentos y promociones
- Seguimiento hasta pago
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from enum import Enum
from typing import Any
from uuid import UUID

from sqlalchemy.orm import Session

from app.modules.shared.services.tax import LEGACY_FALLBACK_TAX_RATE, normalize_tax_rate

logger = logging.getLogger(__name__)


class OrderStatus(str, Enum):
    """Estados de orden."""

    DRAFT = "draft"
    APPROVED = "approved"
    INVOICED = "invoiced"
    SHIPPED = "shipped"
    PAID = "paid"
    CANCELLED = "cancelled"


class CreateSalesOrderUseCase:
    """Crea orden de venta."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        customer_id: UUID,
        lines: list[dict[str, Any]],
        tax_rate: Decimal = LEGACY_FALLBACK_TAX_RATE,
        notes: str | None = None,
        due_date: datetime | None = None,
    ) -> dict[str, Any]:
        """
        Crea orden de venta en draft.

        Args:
            customer_id: Customer ID
            lines: List of {product_id, qty, unit_price, discount_pct}
            notes: Notas de orden
            due_date: Fecha de entrega

        Returns:
            {
                "order_id": UUID,
                "order_number": str,
                "status": "draft",
                "customer_id": UUID,
                "subtotal": Decimal,
                "discount": Decimal,
                "tax": Decimal,
                "total": Decimal,
                "created_at": datetime
            }
        """
        subtotal = Decimal("0")
        total_discount = Decimal("0")
        total_tax = Decimal("0")
        default_tax_rate = normalize_tax_rate(tax_rate) or LEGACY_FALLBACK_TAX_RATE

        for line in lines:
            qty = Decimal(str(line.get("qty", 0)))
            unit_price = Decimal(str(line.get("unit_price", 0)))
            discount_pct = Decimal(str(line.get("discount_pct", 0))) / 100
            line_tax_rate = normalize_tax_rate(line.get("tax_rate"))
            effective_tax_rate = line_tax_rate if line_tax_rate is not None else default_tax_rate

            line_subtotal = qty * unit_price
            line_discount = line_subtotal * discount_pct
            line_net = line_subtotal - line_discount

            subtotal += line_subtotal
            total_discount += line_discount
            total_tax += line_net * effective_tax_rate

        tax = total_tax
        total = subtotal - total_discount + total_tax

        return {
            "order_id": UUID(int=0),  # Set by repo
            "order_number": "",  # Generated by repo
            "customer_id": customer_id,
            "status": "draft",
            "subtotal": subtotal,
            "discount": total_discount,
            "tax": tax,
            "total": total,
            "lines": lines,
            "notes": notes,
            "due_date": due_date,
            "created_at": datetime.now(UTC),
        }


class ApproveSalesOrderUseCase:
    """Aprueba orden de venta."""

    # STUB: no conectado al flujo real — no usar en producción

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
        approved_by: UUID,
    ) -> dict[str, Any]:
        """
        Aprueba orden (transición draft → approved).

        Validaciones:
        - Stock disponible para cada línea
        - Customer activo

        Args:
            order_id: Order ID
            approved_by: User ID que aprueba

        Returns:
            {
                "order_id": UUID,
                "status": "approved",
                "approved_at": datetime,
                "approved_by": UUID
            }
        """
        return {
            "order_id": order_id,
            "status": "approved",
            "approved_at": datetime.now(UTC),
            "approved_by": approved_by,
        }


class CreateInvoiceFromOrderUseCase:
    """Crea factura automáticamente desde orden aprobada."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
        order_number: str,
        customer_id: UUID,
        lines: list[dict[str, Any]],
        subtotal: Decimal,
        tax: Decimal,
    ) -> dict[str, Any]:
        """
        Convierte orden aprobada a factura.

        Transición: approved → invoiced

        Args:
            order_id: Order ID
            order_number: Order number
            customer_id: Customer ID
            lines: Order lines
            subtotal: Subtotal
            tax: Tax

        Returns:
            {
                "invoice_id": UUID,
                "invoice_number": str,
                "order_id": UUID,
                "status": "draft",
                "total": Decimal
            }
        """
        total = subtotal + tax

        return {
            "invoice_id": UUID(int=0),  # Set by repo
            "invoice_number": f"INV-{order_number}",
            "order_id": order_id,
            "customer_id": customer_id,
            "status": "draft",
            "subtotal": subtotal,
            "tax": tax,
            "total": total,
            "created_at": datetime.now(UTC),
        }


class CalculateDiscountUseCase:
    """Calcula descuento para orden."""

    WHOLESALE_DISCOUNT_PCT = Decimal("5.00")
    VOLUME_DISCOUNT_TIERS: tuple[tuple[Decimal, Decimal], ...] = (
        (Decimal("1500"), Decimal("5.00")),
        (Decimal("500"), Decimal("2.00")),
    )
    VOLUME_QTY_TIERS: tuple[tuple[Decimal, Decimal], ...] = (
        (Decimal("25"), Decimal("5.00")),
        (Decimal("10"), Decimal("2.00")),
    )

    def __init__(self, db: Session | None = None):
        self.db = db

    @staticmethod
    def _decimal(value: Any, *, default: Decimal = Decimal("0")) -> Decimal:
        try:
            return Decimal(str(value))
        except (InvalidOperation, TypeError, ValueError):
            return default

    @classmethod
    def _pct_amount(cls, base: Decimal, pct: Decimal) -> Decimal:
        if base <= 0 or pct <= 0:
            return Decimal("0")
        return (base * pct / Decimal("100")).quantize(Decimal("0.01"))

    def _customer_is_wholesale(self, customer_id: UUID, lines: list[dict[str, Any]]) -> bool:
        inline_flag = any(bool(line.get("customer_is_wholesale")) for line in lines)
        if inline_flag:
            return True
        if self.db is None:
            return False
        try:
            from app.models.core.clients import Client

            customer = self.db.get(Client, customer_id)
            return bool(getattr(customer, "is_wholesale", False)) if customer is not None else False
        except Exception:
            logger.exception("Error resolving customer wholesale flag for %s", customer_id)
            return False

    def _volume_discount_pct(self, subtotal: Decimal, lines: list[dict[str, Any]]) -> Decimal:
        total_qty = sum((self._decimal(line.get("qty")) for line in lines), Decimal("0"))

        subtotal_pct = next(
            (pct for threshold, pct in self.VOLUME_DISCOUNT_TIERS if subtotal >= threshold),
            Decimal("0"),
        )
        qty_pct = next(
            (pct for threshold, pct in self.VOLUME_QTY_TIERS if total_qty >= threshold),
            Decimal("0"),
        )
        explicit_pct = max(
            (self._decimal(line.get("volume_discount_pct")) for line in lines),
            default=Decimal("0"),
        )
        return max(subtotal_pct, qty_pct, explicit_pct)

    def _promotion_discount_amount(self, lines: list[dict[str, Any]]) -> Decimal:
        total = Decimal("0")
        for line in lines:
            qty = self._decimal(line.get("qty"))
            unit_price = self._decimal(line.get("unit_price"))
            line_base = qty * unit_price
            promo_amount = self._decimal(line.get("promotion_discount_amount"))
            promo_pct = self._decimal(line.get("promotion_discount_pct"))
            line_total = promo_amount + self._pct_amount(line_base, promo_pct)
            total += min(line_total, line_base if line_base > 0 else Decimal("0"))
        return total.quantize(Decimal("0.01"))

    def execute(
        self,
        *,
        customer_id: UUID,
        subtotal: Decimal,
        lines: list[dict[str, Any]],
    ) -> Decimal:
        """
        Calcula descuento automático basado en:
        - Tipo de cliente (mayorista, minorista)
        - Volumen de compra
        - Promociones activas

        Args:
            customer_id: Customer ID
            subtotal: Subtotal of order
            lines: Order lines

        Returns:
            Total discount amount
        """
        subtotal = self._decimal(subtotal)
        if subtotal <= 0:
            return Decimal("0.00")

        promotion_discount = self._promotion_discount_amount(lines)
        remaining_after_promo = max(subtotal - promotion_discount, Decimal("0"))

        customer_discount_pct = max(
            (self._decimal(line.get("customer_discount_pct")) for line in lines),
            default=Decimal("0"),
        )
        if customer_discount_pct <= 0 and self._customer_is_wholesale(customer_id, lines):
            customer_discount_pct = self.WHOLESALE_DISCOUNT_PCT
        customer_discount = self._pct_amount(remaining_after_promo, customer_discount_pct)

        remaining_after_customer = max(remaining_after_promo - customer_discount, Decimal("0"))
        volume_discount_pct = self._volume_discount_pct(subtotal, lines)
        volume_discount = self._pct_amount(remaining_after_customer, volume_discount_pct)

        total_discount = promotion_discount + customer_discount + volume_discount
        return min(total_discount.quantize(Decimal("0.01")), subtotal.quantize(Decimal("0.01")))


class GetSalesOrderUseCase:
    """Obtiene detalle de orden."""

    # STUB: no conectado al flujo real — no usar en producción

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
    ) -> dict[str, Any]:
        """
        Obtiene orden con todas las líneas.

        Args:
            order_id: Order ID

        Returns:
            {
                "id": UUID,
                "number": str,
                "status": str,
                "customer": {...},
                "lines": [...],
                "subtotal": Decimal,
                "tax": Decimal,
                "total": Decimal,
                "created_at": datetime,
                "approved_at": datetime | None,
                "invoice_id": UUID | None
            }
        """
        return {
            "id": order_id,
            "number": "",
            "status": "draft",
        }


class CancelSalesOrderUseCase:
    """Cancela orden de venta."""

    # STUB: no conectado al flujo real — no usar en producción

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
        reason: str,
        cancelled_by: UUID,
    ) -> dict[str, Any]:
        """
        Cancela orden (reversión a draft).

        No puede cancelar si ya está invoiced/paid.

        Args:
            order_id: Order ID
            reason: Motivo de cancelación
            cancelled_by: User ID que cancela

        Returns:
            {
                "order_id": UUID,
                "status": "cancelled",
                "cancelled_at": datetime,
                "cancelled_by": UUID,
                "reason": str
            }
        """
        return {
            "order_id": order_id,
            "status": "cancelled",
            "cancelled_at": datetime.now(UTC),
            "cancelled_by": cancelled_by,
            "reason": reason,
        }
