"""
SALES MODULE: Use Cases para órdenes de venta.

Implementa:
- Creación de órdenes
- Aprobación
- Conversión a factura
- Descuentos y promociones
- Seguimiento hasta pago
"""

from __future__ import annotations

import logging
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any
from uuid import UUID

logger = logging.getLogger(__name__)


class OrderStatus(str, Enum):
    """Estados de orden."""

    DRAFT = "draft"
    APPROVED = "approved"
    INVOICED = "invoiced"
    SHIPPED = "shipped"
    PAID = "paid"
    CANCELLED = "cancelled"


class CreateSalesOrderUseCase:
    """Crea orden de venta."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        customer_id: UUID,
        lines: list[dict[str, Any]],
        notes: str | None = None,
        due_date: datetime | None = None,
    ) -> dict[str, Any]:
        """
        Crea orden de venta en draft.

        Args:
            customer_id: Customer ID
            lines: List of {product_id, qty, unit_price, discount_pct}
            notes: Notas de orden
            due_date: Fecha de entrega

        Returns:
            {
                "order_id": UUID,
                "order_number": str,
                "status": "draft",
                "customer_id": UUID,
                "subtotal": Decimal,
                "discount": Decimal,
                "tax": Decimal,
                "total": Decimal,
                "created_at": datetime
            }
        """
        subtotal = Decimal("0")
        total_discount = Decimal("0")

        for line in lines:
            qty = Decimal(str(line.get("qty", 0)))
            unit_price = Decimal(str(line.get("unit_price", 0)))
            discount_pct = Decimal(str(line.get("discount_pct", 0))) / 100

            line_subtotal = qty * unit_price
            line_discount = line_subtotal * discount_pct

            subtotal += line_subtotal
            total_discount += line_discount

        tax = (subtotal - total_discount) * Decimal("0.21")  # IVA 21%
        total = subtotal - total_discount + tax

        return {
            "order_id": UUID(int=0),  # Set by repo
            "order_number": "",  # Generated by repo
            "customer_id": customer_id,
            "status": "draft",
            "subtotal": subtotal,
            "discount": total_discount,
            "tax": tax,
            "total": total,
            "lines": lines,
            "notes": notes,
            "due_date": due_date,
            "created_at": datetime.utcnow(),
        }


class ApproveSalesOrderUseCase:
    """Aprueba orden de venta."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
        approved_by: UUID,
    ) -> dict[str, Any]:
        """
        Aprueba orden (transición draft → approved).

        Validaciones:
        - Stock disponible para cada línea
        - Customer activo

        Args:
            order_id: Order ID
            approved_by: User ID que aprueba

        Returns:
            {
                "order_id": UUID,
                "status": "approved",
                "approved_at": datetime,
                "approved_by": UUID
            }
        """
        return {
            "order_id": order_id,
            "status": "approved",
            "approved_at": datetime.utcnow(),
            "approved_by": approved_by,
        }


class CreateInvoiceFromOrderUseCase:
    """Crea factura automáticamente desde orden aprobada."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
        order_number: str,
        customer_id: UUID,
        lines: list[dict[str, Any]],
        subtotal: Decimal,
        tax: Decimal,
    ) -> dict[str, Any]:
        """
        Convierte orden aprobada a factura.

        Transición: approved → invoiced

        Args:
            order_id: Order ID
            order_number: Order number
            customer_id: Customer ID
            lines: Order lines
            subtotal: Subtotal
            tax: Tax

        Returns:
            {
                "invoice_id": UUID,
                "invoice_number": str,
                "order_id": UUID,
                "status": "draft",
                "total": Decimal
            }
        """
        total = subtotal + tax

        return {
            "invoice_id": UUID(int=0),  # Set by repo
            "invoice_number": f"INV-{order_number}",
            "order_id": order_id,
            "customer_id": customer_id,
            "status": "draft",
            "subtotal": subtotal,
            "tax": tax,
            "total": total,
            "created_at": datetime.utcnow(),
        }


class CalculateDiscountUseCase:
    """Calcula descuento para orden."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        customer_id: UUID,
        subtotal: Decimal,
        lines: list[dict[str, Any]],
    ) -> Decimal:
        """
        Calcula descuento automático basado en:
        - Tipo de cliente (mayorista, minorista)
        - Volumen de compra
        - Promociones activas

        Args:
            customer_id: Customer ID
            subtotal: Subtotal of order
            lines: Order lines

        Returns:
            Total discount amount
        """
        # TODO: Implement discount rules engine
        # - Check customer tier (wholesale vs retail)
        # - Check volume-based discounts
        # - Check active promotions
        # - Check product-specific discounts

        return Decimal("0")


class GetSalesOrderUseCase:
    """Obtiene detalle de orden."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
    ) -> dict[str, Any]:
        """
        Obtiene orden con todas las líneas.

        Args:
            order_id: Order ID

        Returns:
            {
                "id": UUID,
                "number": str,
                "status": str,
                "customer": {...},
                "lines": [...],
                "subtotal": Decimal,
                "tax": Decimal,
                "total": Decimal,
                "created_at": datetime,
                "approved_at": datetime | None,
                "invoice_id": UUID | None
            }
        """
        return {
            "id": order_id,
            "number": "",
            "status": "draft",
        }


class CancelSalesOrderUseCase:
    """Cancela orden de venta."""

    def __init__(self):
        pass

    def execute(
        self,
        *,
        order_id: UUID,
        reason: str,
        cancelled_by: UUID,
    ) -> dict[str, Any]:
        """
        Cancela orden (reversión a draft).

        No puede cancelar si ya está invoiced/paid.

        Args:
            order_id: Order ID
            reason: Motivo de cancelación
            cancelled_by: User ID que cancela

        Returns:
            {
                "order_id": UUID,
                "status": "cancelled",
                "cancelled_at": datetime,
                "cancelled_by": UUID,
                "reason": str
            }
        """
        return {
            "order_id": order_id,
            "status": "cancelled",
            "cancelled_at": datetime.utcnow(),
            "cancelled_by": cancelled_by,
            "reason": reason,
        }
