export const TENANT_IMPORTADOR = {
  upload: '/api/v1/importador/upload',
  run: '/api/v1/importador/run',
  runAsync: '/api/v1/importador/run-async',
  documents: '/api/v1/importador/documents',
  documentById: (id: string) => `/api/v1/importador/documents/${id}`,
  confirm: (id: string) => `/api/v1/importador/documents/${id}/confirm`,
  save: (id: string) => `/api/v1/importador/documents/${id}/save`,
  saveProducts: (id: string) => `/api/v1/importador/documents/${id}/save-as-products`,
  syncRecipe: (id: string) => `/api/v1/importador/documents/${id}/sync_recipe`,
  syncRecipes: (id: string) => `/api/v1/importador/documents/${id}/sync_recipes`,
  edit: (id: string) => `/api/v1/importador/documents/${id}/edit`,
  reject: (id: string) => `/api/v1/importador/documents/${id}/reject`,
  logs: (id: string) => `/api/v1/importador/documents/${id}/logs`,
  dashboard: '/api/v1/importador/dashboard',
  batches: '/api/v1/importador/batches',
  batchById: (id: string) => `/api/v1/importador/batches/${id}`,
  docCategories: '/api/v1/importador/doc-categories',
  // Recipes
  recipes: '/api/v1/importador/recipes',
  recipeById: (id: string) => `/api/v1/importador/recipes/${id}`,
  recipeDrafts: (recipeId: string) => `/api/v1/importador/recipes/${recipeId}/drafts`,
  draftById: (id: string) => `/api/v1/importador/drafts/${id}`,
  draftSnapshot: (draftId: string) => `/api/v1/importador/drafts/${draftId}/snapshot`,
  recipeSnapshots: (recipeId: string) => `/api/v1/importador/recipes/${recipeId}/snapshots`,
  snapshotById: (id: string) => `/api/v1/importador/snapshots/${id}`,
  saveDailyLog: (id: string) => `/api/v1/importador/documents/${id}/save-as-daily-log`,
  purgeAll: '/api/v1/importador/purge-all',
}
