export const TENANT_IMPORTADOR = {
  runAsync: '/api/v1/importador/run-async',
  documents: '/api/v1/importador/documents',
  documentById: (id: string) => `/api/v1/importador/documents/${id}`,
  confirm: (id: string) => `/api/v1/importador/documents/${id}/confirm`,
  save: (id: string) => `/api/v1/importador/documents/${id}/save`,
  saveProducts: (id: string) => `/api/v1/importador/documents/${id}/save-as-products`,
  syncRecipe: (id: string) => `/api/v1/importador/documents/${id}/sync_recipe`,
  syncRecipes: (id: string) => `/api/v1/importador/documents/${id}/sync_recipes`,
  edit: (id: string) => `/api/v1/importador/documents/${id}/edit`,
  reject: (id: string) => `/api/v1/importador/documents/${id}/reject`,
  dashboard: '/api/v1/importador/dashboard',
  batches: '/api/v1/importador/batches',
  batchById: (id: string) => `/api/v1/importador/batches/${id}`,
  batchStream: (id: string) => `/api/v1/importador/batches/${id}/stream`,
  canonicalFields: '/api/v1/importador/canonical-fields',
  docCategories: '/api/v1/importador/doc-categories',
  fileSupport: '/api/v1/importador/file-support',
  productSheetConfig: '/api/v1/importador/product-sheet-config',
  // Recipes
  recipes: '/api/v1/importador/recipes',
  recipeById: (id: string) => `/api/v1/importador/recipes/${id}`,
  recipeDrafts: (recipeId: string) => `/api/v1/importador/recipes/${recipeId}/drafts`,
  draftById: (id: string) => `/api/v1/importador/drafts/${id}`,
  draftSnapshot: (draftId: string) => `/api/v1/importador/drafts/${draftId}/snapshot`,
  recipeSnapshots: (recipeId: string) => `/api/v1/importador/recipes/${recipeId}/snapshots`,
  saveDailyLog: (id: string) => `/api/v1/importador/documents/${id}/save-as-daily-log`,
  lineMatchCandidates: (id: string) => `/api/v1/importador/documents/${id}/line-match-candidates`,
  saveCapabilities: '/api/v1/importador/save-capabilities',
  purgeAll: '/api/v1/importador/purge-all',
  lineItemSlots: '/api/v1/importador/line-item-slots',
}
