"""initial schema

Revision ID: 579746cbed78
Revises: 1c8dcf1ea539
Create Date: 2025-08-15 20:26:53.586737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579746cbed78'
down_revision: Union[str, Sequence[str], None] = '1c8dcf1ea539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('ua', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_audit_kind'), 'auth_audit', ['kind'], unique=False)
    op.create_index(op.f('ix_auth_audit_scope'), 'auth_audit', ['scope'], unique=False)
    op.create_index(op.f('ix_auth_audit_tenant_id'), 'auth_audit', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auth_audit_user_id'), 'auth_audit', ['user_id'], unique=False)
    op.create_table('auth_refresh_family',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_refresh_family_revoked_at', 'auth_refresh_family', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_family_tenant_id'), 'auth_refresh_family', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auth_refresh_family_user_id'), 'auth_refresh_family', ['user_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=True)
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_tenant_id'), 'auth_user', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('core_categoriaempresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('core_idioma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('core_moneda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('simbolo', sa.String(length=5), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('core_permisoaccionglobal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('core_rolbase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('permisos', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('core_tipoempresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('core_tiponegocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('modulos_modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('icono', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('plantilla_inicial', sa.String(length=255), nullable=False),
    sa.Column('context_type', sa.String(length=10), nullable=False),
    sa.Column('modelo_objetivo', sa.String(length=255), nullable=True),
    sa.Column('filtros_contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulos_modulo_id'), 'modulos_modulo', ['id'], unique=False)
    op.create_table('auth_refresh_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('prev_jti', sa.UUID(), nullable=True),
    sa.Column('ua_hash', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['auth_refresh_family.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_auth_refresh_token_expires_at', 'auth_refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_token_family_id'), 'auth_refresh_token', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_refresh_token_jti'), 'auth_refresh_token', ['jti'], unique=True)
    op.create_index(op.f('ix_auth_refresh_token_prev_jti'), 'auth_refresh_token', ['prev_jti'], unique=False)
    op.create_table('core_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('tipo_empresa_id', sa.Integer(), nullable=True),
    sa.Column('tipo_negocio_id', sa.Integer(), nullable=True),
    sa.Column('ruc', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('cp', sa.String(length=20), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('motivo_desactivacion', sa.Text(), nullable=True),
    sa.Column('plantilla_inicio', sa.String(length=100), nullable=False),
    sa.Column('sitio_web', sa.String(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_empresa_id'], ['core_tipoempresa.id'], ),
    sa.ForeignKeyConstraint(['tipo_negocio_id'], ['core_tiponegocio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('core_horarioatencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.String(length=5), nullable=False),
    sa.Column('fin', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['dia_id'], ['core_dia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_sectorplantilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo_empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_negocio_id', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_empresa_id'], ['core_tipoempresa.id'], ),
    sa.ForeignKeyConstraint(['tipo_negocio_id'], ['core_tiponegocio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('identificacion', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('localidad', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('core_configuracionempresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('idioma_predeterminado', sa.String(length=10), nullable=False),
    sa.Column('zona_horaria', sa.String(length=50), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('logo_empresa', sa.String(length=100), nullable=True),
    sa.Column('color_secundario', sa.String(length=7), nullable=False),
    sa.Column('color_primario', sa.String(length=7), nullable=False),
    sa.Column('permitir_roles_personalizados', sa.Boolean(), nullable=False),
    sa.Column('limite_usuarios', sa.Integer(), nullable=False),
    sa.Column('dias_laborales', sa.JSON(), nullable=False),
    sa.Column('horario_atencion', sa.JSON(), nullable=False),
    sa.Column('tipo_operacion', sa.String(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=True),
    sa.Column('rfc', sa.String(), nullable=True),
    sa.Column('regimen_fiscal', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('idioma_id', sa.Integer(), nullable=True),
    sa.Column('moneda_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['idioma_id'], ['core_idioma.id'], ),
    sa.ForeignKeyConstraint(['moneda_id'], ['core_moneda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_index(op.f('ix_core_configuracionempresa_id'), 'core_configuracionempresa', ['id'], unique=False)
    op.create_table('core_configuracioninventarioempresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('control_stock_activo', sa.Boolean(), nullable=False),
    sa.Column('notificar_bajo_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_minimo_global', sa.Integer(), nullable=True),
    sa.Column('um_predeterminadas', sa.JSON(), nullable=True),
    sa.Column('categorias_personalizadas', sa.Boolean(), nullable=False),
    sa.Column('campos_extra_producto', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_index(op.f('ix_core_configuracioninventarioempresa_id'), 'core_configuracioninventarioempresa', ['id'], unique=False)
    op.create_table('core_rolempresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('permisos', sa.JSON(), nullable=False),
    sa.Column('rol_base_id', sa.Integer(), nullable=True),
    sa.Column('creado_por_empresa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['rol_base_id'], ['core_rolbase.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_empresa_rol')
    )
    op.create_table('datos_importados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('hash', name='uq_hash_documento')
    )
    op.create_index(op.f('ix_datos_importados_id'), 'datos_importados', ['id'], unique=False)
    op.create_table('modulos_empresamodulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_activacion', sa.Date(), nullable=False),
    sa.Column('fecha_expiracion', sa.Date(), nullable=True),
    sa.Column('plantilla_inicial', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos_modulo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'modulo_id', name='modulos_empresamodulo_empresa_id_modulo_id_uniq')
    )
    op.create_index(op.f('ix_modulos_empresamodulo_id'), 'modulos_empresamodulo', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('product_metadata', sa.JSON(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('usuarios_usuarioempresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_encargado', sa.String(length=100), nullable=False),
    sa.Column('apellido_encargado', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_admin_empresa', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('password_token_created', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_usuarioempresa_email'), 'usuarios_usuarioempresa', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_usuarioempresa_id'), 'usuarios_usuarioempresa', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_usuarioempresa_tenant_id'), 'usuarios_usuarioempresa', ['tenant_id'], unique=False)
    op.create_table('auditoria_importacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cambios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_usuarioempresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_importacion_documento_id'), 'auditoria_importacion', ['documento_id'], unique=False)
    op.create_index(op.f('ix_auditoria_importacion_id'), 'auditoria_importacion', ['id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=False),
    sa.Column('banco', sa.String(), nullable=True),
    sa.Column('moneda', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_empresa_id'), 'bank_accounts', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_iban'), 'bank_accounts', ['iban'], unique=False)
    op.create_table('core_perfilusuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=10), nullable=False),
    sa.Column('zona_horaria', sa.String(length=50), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_usuarioempresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('fecha_emision', sa.String(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    op.create_table('facturas_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('archivo_nombre', sa.String(), nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_importacion', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_usuarioempresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_temp_id'), 'facturas_temp', ['id'], unique=False)
    op.create_table('modulos_moduloasignado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.Column('ver_modulo_auto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos_modulo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_usuarioempresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'modulo_id', 'empresa_id', name='modulos_moduloasignado_usuario_id_modulo_id_empresa_id_uniq')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('yield_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_table('usuarios_usuariorolempresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('asignado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por_id'], ['usuarios_usuarioempresa.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['core_rolempresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_usuarioempresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_usuariorolempresa_id'), 'usuarios_usuariorolempresa', ['id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('RECIBO', 'TRANSFERENCIA', 'TARJETA', 'EFECTIVO', 'OTRO', name='movimientotipo'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONCILIADO', 'RECHAZADO', name='movimientoestado'), nullable=False),
    sa.Column('concepto', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('contrapartida_nombre', sa.String(), nullable=True),
    sa.Column('contrapartida_iban', sa.String(), nullable=True),
    sa.Column('banco_contraparte', sa.String(), nullable=True),
    sa.Column('comision', sa.Float(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('adjunto_url', sa.String(), nullable=True),
    sa.Column('sepa_end_to_end_id', sa.String(), nullable=True),
    sa.Column('sepa_creditor_id', sa.String(), nullable=True),
    sa.Column('sepa_mandate_ref', sa.String(), nullable=True),
    sa.Column('esquema_sepa', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('origen', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_cuenta_id'), 'bank_transactions', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_empresa_id'), 'bank_transactions', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_fecha'), 'bank_transactions', ['fecha'], unique=False)
    op.create_table('invoice_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)
    op.create_table('internal_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tx_origen_id', sa.Integer(), nullable=False),
    sa.Column('tx_destino_id', sa.Integer(), nullable=False),
    sa.Column('cambio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['tx_destino_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['tx_origen_id'], ['bank_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_transfers_empresa_id'), 'internal_transfers', ['empresa_id'], unique=False)
    op.create_table('lineas_panaderia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_pan', sa.String(), nullable=False),
    sa.Column('gramos', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invoice_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repuesto', sa.String(), nullable=False),
    sa.Column('horas_mano_obra', sa.Float(), nullable=False),
    sa.Column('tarifa', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['invoice_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('bank_tx_id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe_aplicado', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bank_tx_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['core_empresa.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_bank_tx_id'), 'payments', ['bank_tx_id'], unique=False)
    op.create_index(op.f('ix_payments_empresa_id'), 'payments', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_payments_factura_id'), 'payments', ['factura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_factura_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_empresa_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bank_tx_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('lineas_taller')
    op.drop_table('lineas_panaderia')
    op.drop_index(op.f('ix_internal_transfers_empresa_id'), table_name='internal_transfers')
    op.drop_table('internal_transfers')
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_table('invoice_line')
    op.drop_index(op.f('ix_bank_transactions_fecha'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_empresa_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_cuenta_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_usuarios_usuariorolempresa_id'), table_name='usuarios_usuariorolempresa')
    op.drop_table('usuarios_usuariorolempresa')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('modulos_moduloasignado')
    op.drop_index(op.f('ix_facturas_temp_id'), table_name='facturas_temp')
    op.drop_table('facturas_temp')
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_table('core_perfilusuario')
    op.drop_index(op.f('ix_bank_accounts_iban'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_empresa_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_auditoria_importacion_id'), table_name='auditoria_importacion')
    op.drop_index(op.f('ix_auditoria_importacion_documento_id'), table_name='auditoria_importacion')
    op.drop_table('auditoria_importacion')
    op.drop_index(op.f('ix_usuarios_usuarioempresa_tenant_id'), table_name='usuarios_usuarioempresa')
    op.drop_index(op.f('ix_usuarios_usuarioempresa_id'), table_name='usuarios_usuarioempresa')
    op.drop_index(op.f('ix_usuarios_usuarioempresa_email'), table_name='usuarios_usuarioempresa')
    op.drop_table('usuarios_usuarioempresa')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_modulos_empresamodulo_id'), table_name='modulos_empresamodulo')
    op.drop_table('modulos_empresamodulo')
    op.drop_index(op.f('ix_datos_importados_id'), table_name='datos_importados')
    op.drop_table('datos_importados')
    op.drop_table('core_rolempresa')
    op.drop_index(op.f('ix_core_configuracioninventarioempresa_id'), table_name='core_configuracioninventarioempresa')
    op.drop_table('core_configuracioninventarioempresa')
    op.drop_index(op.f('ix_core_configuracionempresa_id'), table_name='core_configuracionempresa')
    op.drop_table('core_configuracionempresa')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('core_sectorplantilla')
    op.drop_table('core_horarioatencion')
    op.drop_table('core_empresa')
    op.drop_index(op.f('ix_auth_refresh_token_prev_jti'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_jti'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_family_id'), table_name='auth_refresh_token')
    op.drop_index('ix_auth_refresh_token_expires_at', table_name='auth_refresh_token')
    op.drop_table('auth_refresh_token')
    op.drop_index(op.f('ix_modulos_modulo_id'), table_name='modulos_modulo')
    op.drop_table('modulos_modulo')
    op.drop_table('core_tiponegocio')
    op.drop_table('core_tipoempresa')
    op.drop_table('core_rolbase')
    op.drop_table('core_permisoaccionglobal')
    op.drop_table('core_moneda')
    op.drop_table('core_idioma')
    op.drop_table('core_dia')
    op.drop_table('core_categoriaempresa')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_tenant_id'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index(op.f('ix_auth_refresh_family_user_id'), table_name='auth_refresh_family')
    op.drop_index(op.f('ix_auth_refresh_family_tenant_id'), table_name='auth_refresh_family')
    op.drop_index('ix_auth_refresh_family_revoked_at', table_name='auth_refresh_family')
    op.drop_table('auth_refresh_family')
    op.drop_index(op.f('ix_auth_audit_user_id'), table_name='auth_audit')
    op.drop_index(op.f('ix_auth_audit_tenant_id'), table_name='auth_audit')
    op.drop_index(op.f('ix_auth_audit_scope'), table_name='auth_audit')
    op.drop_index(op.f('ix_auth_audit_kind'), table_name='auth_audit')
    op.drop_table('auth_audit')
    # ### end Alembic commands ###
