name: db-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r ops/requirements.txt
      - name: Lint
        run: ruff --version
      - name: Type check
        run: mypy --version
      - name: Duplicate check
        run: python ops/ci/checks.py
      - name: Smoke
        run: python ops/ci/migrate.py


