name: Cloudflare Worker

on:
  push:
    branches: [ main, master ]
    paths:
      - 'workers/**'
  pull_request:
    paths:
      - 'workers/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: workers
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler CLI (pinned)
        run: npm install -g wrangler@3

      - name: Validate Worker config (no publish)
        run: wrangler validate

      - name: Dry-run deploy (bundle only, no publish)
        run: wrangler deploy --dry-run

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: workers
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler CLI (pinned)
        run: npm install -g wrangler@3

      - name: Publish Worker (wrangler publish)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          if [ -z "${CLOUDFLARE_API_TOKEN}" ]; then
            echo "::error ::Missing secret CLOUDFLARE_API_TOKEN" && exit 1
          fi
          if [ -z "${CLOUDFLARE_ACCOUNT_ID}" ]; then
            echo "::warning ::CLOUDFLARE_ACCOUNT_ID not set; ensure it's in wrangler.toml or pass --account-id"
            wrangler publish
          else
            wrangler publish --account-id "$CLOUDFLARE_ACCOUNT_ID"
          fi
